name: Auto Merge on Label

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    if: github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repo (required for gh CLI in some contexts)
        uses: actions/checkout@v4

      - name: Merge PR if labeled automerge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.html_url }} --merge --auto
