name: Auto Merge Pull Request

on:
  pull_request:

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
                  - name: Auto Merge PRs
  # You may pin to the exact commit or the version.
  # uses: MinhOmega/auto-merge@8e93bde49fbb34313a5514c01cc1e4fce1f31042
                    uses: MinhOmega/auto-merge@v1.0.5
                            
